spring:
  application:
    name: EnableEurekaServer

server:
  port: 8000

eureka:
  instance:
    hostname: 127.0.0.1
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 1000
  client:
    service-url:
      defaultZone: http://master:8000/eureka
    fetch-registry: false
    register-with-eureka: false
