spring:
  application:
    name: EurekaClient

server:
  port: 19000

eureka:
  instance:
    lease-expiration-duration-in-seconds: 1
    lease-renewal-interval-in-seconds: 2
  client:
    service-url:
      defaultZone: http://master:8000/eureka